# Generated by Django 5.0.6 on 2024-08-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tour', models.CharField(max_length=100, verbose_name='Nombre del tour')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(max_length=100, verbose_name='Nombre del estado')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Nombre de la ciudad')),
                ('km_recorrido', models.CharField(max_length=100, verbose_name='Distancia')),
                ('tiempo_estimado', models.CharField(max_length=100, verbose_name='Tiempo estimado')),
                ('punto_inicio', models.CharField(max_length=100, verbose_name='Punto de partida')),
                ('costo', models.FloatField(verbose_name='Costo del tour')),
                ('ganancias', models.FloatField(verbose_name='Ganancia')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Foto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inserción')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ['created'],
            },
        ),
    ]
