# Generated by Django 5.0.6 on 2024-08-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
